extraction:
  cpp:
    after_prepare: 
      - python report.py 59
  cobol:
    after_prepare: 
      - python report.py 59
  csharp:
    after_prepare: 
      - python report.py 59
  java:
    after_prepare: 
      - python report.py 59
  javascript:
    after_prepare: 
      - python report.py 59
  python:
    after_prepare: 
      - python report.py 59
